/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [],
        name: "NodeWindPercentTooLarge",
        type: "error",
    },
    {
        inputs: [],
        name: "NonRootNodeNullParent",
        type: "error",
    },
    {
        inputs: [],
        name: "NonRootNodeWindPercentZero",
        type: "error",
    },
    {
        inputs: [],
        name: "RootNodeNonNullParent",
        type: "error",
    },
    {
        inputs: [],
        name: "RootWindPercentNotZero",
        type: "error",
    },
];
class StepTreeLib__factory {
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
StepTreeLib__factory.abi = _abi;
export { StepTreeLib__factory };
