"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileCreation__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "contract ILensHub",
                name: "hub",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [],
        name: "HandleContainsInvalidCharacters",
        type: "error",
    },
    {
        inputs: [],
        name: "HandleFirstCharInvalid",
        type: "error",
    },
    {
        inputs: [],
        name: "HandleLengthInvalid",
        type: "error",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "address",
                        name: "to",
                        type: "address",
                    },
                    {
                        internalType: "string",
                        name: "handle",
                        type: "string",
                    },
                    {
                        internalType: "string",
                        name: "imageURI",
                        type: "string",
                    },
                    {
                        internalType: "address",
                        name: "followModule",
                        type: "address",
                    },
                    {
                        internalType: "bytes",
                        name: "followModuleInitData",
                        type: "bytes",
                    },
                    {
                        internalType: "string",
                        name: "followNFTURI",
                        type: "string",
                    },
                ],
                internalType: "struct DataTypes.CreateProfileData",
                name: "vars",
                type: "tuple",
            },
        ],
        name: "proxyCreateProfile",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ProfileCreation__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
ProfileCreation__factory.abi = _abi;
exports.ProfileCreation__factory = ProfileCreation__factory;
