"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferStep__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TransferStep__factory_1 = require("./TransferStep__factory");
Object.defineProperty(exports, "TransferStep__factory", { enumerable: true, get: function () { return TransferStep__factory_1.TransferStep__factory; } });
