"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VaultDeployer__factory = exports.Vault__factory = exports.StepTreeLib__factory = exports.PriceAggregator__factory = exports.PriceAggreagtor__factory = exports.FeeController__factory = exports.DremHub__factory = exports.AssetRegistry__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AssetRegistry__factory_1 = require("./AssetRegistry__factory");
Object.defineProperty(exports, "AssetRegistry__factory", { enumerable: true, get: function () { return AssetRegistry__factory_1.AssetRegistry__factory; } });
var DremHub__factory_1 = require("./DremHub__factory");
Object.defineProperty(exports, "DremHub__factory", { enumerable: true, get: function () { return DremHub__factory_1.DremHub__factory; } });
var FeeController__factory_1 = require("./FeeController__factory");
Object.defineProperty(exports, "FeeController__factory", { enumerable: true, get: function () { return FeeController__factory_1.FeeController__factory; } });
var PriceAggreagtor__factory_1 = require("./PriceAggreagtor__factory");
Object.defineProperty(exports, "PriceAggreagtor__factory", { enumerable: true, get: function () { return PriceAggreagtor__factory_1.PriceAggreagtor__factory; } });
var PriceAggregator__factory_1 = require("./PriceAggregator__factory");
Object.defineProperty(exports, "PriceAggregator__factory", { enumerable: true, get: function () { return PriceAggregator__factory_1.PriceAggregator__factory; } });
var StepTreeLib__factory_1 = require("./StepTreeLib__factory");
Object.defineProperty(exports, "StepTreeLib__factory", { enumerable: true, get: function () { return StepTreeLib__factory_1.StepTreeLib__factory; } });
var Vault__factory_1 = require("./Vault__factory");
Object.defineProperty(exports, "Vault__factory", { enumerable: true, get: function () { return Vault__factory_1.Vault__factory; } });
var VaultDeployer__factory_1 = require("./VaultDeployer__factory");
Object.defineProperty(exports, "VaultDeployer__factory", { enumerable: true, get: function () { return VaultDeployer__factory_1.VaultDeployer__factory; } });
